# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Studie/E5ADD/Newfolder/hdl-master/Boards/MINIZED/minized_mic.xdc

# XDC: D:/Studie/E5ADD/Newfolder/hdl-master/Boards/MINIZED/minized_pins.xdc

# XDC: D:/Studie/E5ADD/Newfolder/hdl-master/Boards/MINIZED/minized_LEDs.xdc

# Block Designs: bd/minized_mic/minized_mic.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic || ORIG_REF_NAME==minized_mic} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_processing_system7_0_0/minized_mic_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_processing_system7_0_0 || ORIG_REF_NAME==minized_mic_processing_system7_0_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_axi_gpio_0_0/minized_mic_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_axi_gpio_0_0 || ORIG_REF_NAME==minized_mic_axi_gpio_0_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_axi_gpio_1_0/minized_mic_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_axi_gpio_1_0 || ORIG_REF_NAME==minized_mic_axi_gpio_1_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_xbar_0/minized_mic_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_xbar_0 || ORIG_REF_NAME==minized_mic_xbar_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_auto_pc_0/minized_mic_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_auto_pc_0 || ORIG_REF_NAME==minized_mic_auto_pc_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_ps7_0_axi_periph_0/minized_mic_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_ps7_0_axi_periph_0 || ORIG_REF_NAME==minized_mic_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_rst_ps7_0_100M_0/minized_mic_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_rst_ps7_0_100M_0 || ORIG_REF_NAME==minized_mic_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_pdm_filt_0_0/minized_mic_pdm_filt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_pdm_filt_0_0 || ORIG_REF_NAME==minized_mic_pdm_filt_0_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_microphone_mgr_0_0/minized_mic_microphone_mgr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_microphone_mgr_0_0 || ORIG_REF_NAME==minized_mic_microphone_mgr_0_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_ila_0_0/minized_mic_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_ila_0_0 || ORIG_REF_NAME==minized_mic_ila_0_0} -quiet] -quiet

# IP: bd/minized_mic/ip/minized_mic_ila_1_0/minized_mic_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_mic_ila_1_0 || ORIG_REF_NAME==minized_mic_ila_1_0} -quiet] -quiet

# XDC: bd/minized_mic/minized_mic_ooc.xdc
