# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_processing_system7_0_0/minized_mic_processing_system7_0_0.xci
# IP: The module: 'minized_mic_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_processing_system7_0_0/minized_mic_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_mic_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_processing_system7_0_0/minized_mic_processing_system7_0_0.xci
# IP: The module: 'minized_mic_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_processing_system7_0_0/minized_mic_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_mic_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
