# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/minized_mic_pdm_filt_0_0.xci
# IP: The module: 'minized_mic_pdm_filt_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/pdm_filt_fir_compiler_v7_2_i0/pdm_filt_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pdm_filt_fir_compiler_v7_2_i0 || ORIG_REF_NAME==pdm_filt_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/pdm_filt_fir_compiler_v7_2_i1/pdm_filt_fir_compiler_v7_2_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pdm_filt_fir_compiler_v7_2_i1 || ORIG_REF_NAME==pdm_filt_fir_compiler_v7_2_i1} -quiet] -quiet

# XDC: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/constrs/pdm_filt.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_mic_pdm_filt_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/pdm_filt_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pdm_filt_fir_compiler_v7_2_i0 || ORIG_REF_NAME==pdm_filt_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/pdm_filt_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pdm_filt_fir_compiler_v7_2_i1 || ORIG_REF_NAME==pdm_filt_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/minized_mic_pdm_filt_0_0.xci
# IP: The module: 'minized_mic_pdm_filt_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/pdm_filt_fir_compiler_v7_2_i0/pdm_filt_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pdm_filt_fir_compiler_v7_2_i0 || ORIG_REF_NAME==pdm_filt_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/pdm_filt_fir_compiler_v7_2_i1/pdm_filt_fir_compiler_v7_2_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pdm_filt_fir_compiler_v7_2_i1 || ORIG_REF_NAME==pdm_filt_fir_compiler_v7_2_i1} -quiet] -quiet

# XDC: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/constrs/pdm_filt.xdc
# XDC: The top module name and the constraint reference have the same name: 'minized_mic_pdm_filt_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/pdm_filt_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pdm_filt_fir_compiler_v7_2_i0 || ORIG_REF_NAME==pdm_filt_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/solbj/AppData/Roaming/Xilinx/Projects/minized_mic/MINIZED_2019_1/minized_mic.srcs/sources_1/bd/minized_mic/ip/minized_mic_pdm_filt_0_0/pdm_filt_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pdm_filt_fir_compiler_v7_2_i1 || ORIG_REF_NAME==pdm_filt_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
